# Generated by Django 4.2.5 on 2023-09-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
