# Generated by Django 4.2.5 on 2023-10-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='demo.OrderPosition', to='demo.product'),
        ),
    ]
