# примеры API-запросов

@baseUrl = https://127.0.0.1:8000/api

# получение объявлений
GET http://127.0.0.1:8000/api/advertisements/
Content-Type: application/json

###

# создание объявления
POST http://127.0.0.1:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 411f98748135d4b008ec2ba21decead4769f9682

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://127.0.0.1:8000/api/advertisements/1/
Content-Type: application/json
Authorization: Token 411f98748135d4b008ec2ba21decead4769f9682

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://127.0.0.1:8000/api/advertisements/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET http://127.0.0.1:8000/api/advertisements/?created_at_before=2023-10-25
Content-Type: application/json
