# Generated by Django 4.2.5 on 2023-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='delete',
            field=models.BooleanField(default=False, null=True, verbose_name='Удалить?'),
        ),
    ]
