# Generated by Django 4.2.5 on 2023-10-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scope_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='delete',
        ),
    ]
