# Generated by Django 4.2.5 on 2023-10-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='dt',
            new_name='created_at',
        ),
    ]
