# Generated by Django 4.2.5 on 2023-10-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_id',
            new_name='sensor',
        ),
    ]
