# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидор2",
  "description": "Лучшие помидоры на рынке2"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки в мире"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=пом
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "новый склад",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/1/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=4
Content-Type: application/json
